NurseEqServices/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns

from django.conf.urls.static import static
from NurseEqServices import settings
from django.views.i18n import set_language

urlpatterns = [
                  path('i18n/setlang/', set_language, name='set_language'),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('', include('appointment.urls')),
    path('user/', include('user.urls')),
    path('equipment-res/', include('equipmentReservation.urls')),
    path('accounts/', include('allauth.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
)
# Mohammad@079

appointment/urls.py
from django.urls import path

from appointment.views import AppointmentCreateView, UserAppointment, UserAppointmentUpdateView, ThanksPage, \
    EmergencyAppointmentCreateView, UserAppointmentDeleteView

urlpatterns = [
    path('create/appointment', AppointmentCreateView.as_view(), name='create-appointment'),
    path('user/update/appointment/<int:pk>', UserAppointmentUpdateView.as_view(), name='user-update-appointment'),
    path('list/user/appointemt', UserAppointment.as_view(), name='list-user-appointment'),
    path('delete/page/<int:pk>', UserAppointmentDeleteView.as_view(), name='delete-page'),
    path('thank-you', ThanksPage.as_view(), name='thanks-page'),

    path('create/emergency/appointment', EmergencyAppointmentCreateView.as_view(), name='create-emergency-appointment'),
]

main/urls.py
from django.urls import path

from main.views import MainTemplate, AboutUsTemplateView, DepartmentsTemplateView, ContactTemplateView, ServicesTemplateView
from django.conf.urls.static import static
from NurseEqServices import settings
urlpatterns = [
    path('', MainTemplate.as_view(), name='home'),
    path('about_us', AboutUsTemplateView.as_view(), name='about-us'),
    path('services/', ServicesTemplateView.as_view(), name='services'),
    path('departments/', DepartmentsTemplateView.as_view(), name='departments'),
    path('contact_us/', ContactTemplateView.as_view(), name='contact-us'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointment/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
from user.models import CustomUser, Staff, CITIES

WORKING_HOURS = (('', _('--- Choose Session time ---')),
                 ('8-9', '08:00 AM - 09:00 AM'), ('9-10', '09:00 AM - 10:00 AM'), ('10-11', '10:00 AM - 11:00 AM'),
                 ('11-12', '11:00 AM - 12:00 PM'), ('12-1', '12:00 PM - 01:00 PM'), ('1-2', '01:00 PM - 02:00 PM'),
                 ('2-3', '02:00 PM - 03:00 PM'), ('3-4', '03:00 PM - 04:00 PM'), ('4-5', '04:00 PM - 05:00 PM'),
                 ('5-6', '05:00 PM - 06:00 PM'),)

APPOINTMENT_STATUS = (('AVAILABLE', _('Available')), ('BOOKED', _('Booked')),
                      ('APPROVED', _('Approved')), ('UNAVAILABLE', _('Unavailable')),
                      ('DONE', _('Done')),
                      )

MAJOR = (('', _('--- Choose Major ---')), ('Pediatric', _('Pediatric nursing')), ('Elderly', _('Elderly nursing')),
         ('Kidney', _('Kidney disease')), ('Other', _('Other')),
         )

APPOINTMENT_TYPE = (('EMERGENCY', _('Emergency')), ('NORMAL', _('Normal')),)


class Appointment(models.Model):
    date = models.DateField()
    major = models.CharField(max_length=255, choices=MAJOR, null=True)
    session_time = models.CharField(max_length=255, choices=WORKING_HOURS, null=True)
    message = models.TextField(null=True, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    doctor = models.ForeignKey(Staff, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=255, choices=APPOINTMENT_STATUS, null=True, default='AVAILABLE')
    type = models.CharField(max_length=255, choices=APPOINTMENT_TYPE, null=True, default='NORMAL')
    city = models.CharField(max_length=255, choices=CITIES, null=True,)

    def __str__(self):
        return f'{self.message} --------- appointment made by: {self.user}'

appointment/forms.py
import datetime
from crispy_forms.helper import FormHelper
from django import forms
from crispy_forms.layout import Layout, Div, ButtonHolder, Submit
from django.utils.translation import ugettext_lazy as _

from appointment.models import Appointment, WORKING_HOURS
from user.models import Staff


class DateInput(forms.DateInput):
    input_type = 'date'


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['major', 'date', 'city', 'session_time', 'message']
        widgets = {
            'date': DateInput(),
            'message': forms.widgets.Textarea(attrs={'placeholder': _('Write your notes here (optional)')}),
        }

    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            # Div(
            Div("city", css_class="col-md-6 input-block"),
            Div("major", css_class="col-md-6 input-block"),
            Div("date", css_class="col-md-6 input-block"),
            Div("session_time", css_class="col-md-6 input-block"),
            Div("message", css_class="col-md-12"),
            Div(ButtonHolder(Submit('submit', _('Submit'), css_class='mt-2 w-25'),
                             css_class='d-flex justify-content-center'), )
        )

    def clean(self):
        clean = super(AppointmentForm, self).clean()
        clean['date'] = self.cleaned_data['date']
        if clean['date'] < datetime.date.today():
            raise forms.ValidationError("The date cannot be in the past!")

        clean['session_time'] = self.cleaned_data['session_time']
        if Appointment.objects.filter(date=clean['date'], session_time=clean['session_time'],
                                      status='PENDING' or 'APPROVED' or 'UNAVAILABLE').exists():
            raise forms.ValidationError("This time is not available, please Choose another time!")

        return clean


# ---------------------------------------

class EmergencyAppointmentForm(forms.ModelForm):
    user = forms.CharField()
    phone = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = Appointment
        fields = ['city', 'date', 'message']
        widgets = {
            'message': forms.widgets.Textarea(attrs={'placeholder': _('Write your note here (optional)')}),
        }

    def __init__(self, *args, **kwargs):
        if kwargs.get('user'):
            self.user = kwargs.pop('user', None)

        super(EmergencyAppointmentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.fields['user'].widget.attrs['readonly'] = True
        self.fields['phone'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['date'].widget.attrs['readonly'] = True
        self.fields['date'].initial = datetime.date.today()
        self.fields['user'].initial = self.user
        self.fields['phone'].initial = self.user.phone
        self.fields['email'].initial = self.user.email
        self.helper.layout = Layout(
            # Div(
            Div("user", css_class="col-md-4 input-block"),
            Div("phone", css_class="col-md-4 input-block"),
            Div("email", css_class="col-md-4 input-block"),
            Div("date", css_class="col-md-6 input-block"),
            Div("city", css_class="col-md-6 input-block"),
            Div("message", css_class="col-md-12"),
            Div(ButtonHolder(Submit('submit', _('Submit'), css_class='mt-2 w-25'),
                             css_class='d-flex justify-content-center'), )
        )

appointment/views.py
import datetime
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages

from appointment.forms import AppointmentForm, EmergencyAppointmentForm
from appointment.models import Appointment
from equipmentReservation.models import EquipmentReservation
from user.models import Staff


@method_decorator(login_required, name="dispatch")
class AppointmentCreateView(CreateView):
    model = Appointment
    form_class = AppointmentForm
    template_name = 'partials/appointment/create_appointment.html'
    success_url = reverse_lazy('thanks-page')

    # success_message = _('Your request sent successfully.')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.status = 'BOOKED'
        form.instance.type = 'NORMAL'
        form.instance.doctor = Staff.objects.filter(city=self.request.POST['city']).order_by('?')[0]
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class UserAppointmentUpdateView(SuccessMessageMixin, UpdateView):
    template_name = 'partials/appointment/update_appointment.html'
    model = Appointment
    form_class = AppointmentForm
    success_message = _('Your appointment updated successfully.')
    success_url = reverse_lazy('list-user-appointment')


@method_decorator(login_required, name="dispatch")
class UserAppointment(ListView):
    model = Appointment
    template_name = 'partials/appointment/list_user_appointment.html'

    # paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserAppointment, self).get_context_data()
        context['appointment'] = self.model.objects.filter(user=self.request.user)
        context['eq_reservation'] = EquipmentReservation.objects.filter(user=self.request.user)
        return context


@method_decorator(login_required, name="dispatch")
class UserAppointmentDeleteView(SuccessMessageMixin, DeleteView):
    template_name = 'partials/delete_page.html'
    model = Appointment
    success_message = _('Your appointment have been delete successfully.')
    success_url = reverse_lazy('list-user-appointment')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(UserAppointmentDeleteView, self).delete(request, *args, **kwargs)


@method_decorator(login_required, name="dispatch")
class ThanksPage(TemplateView):
    model = Appointment
    template_name = 'templates/partials/appointment/thanks_page.html'


@method_decorator(login_required, name="dispatch")
class EmergencyAppointmentCreateView(SuccessMessageMixin, CreateView):
    model = Appointment
    form_class = EmergencyAppointmentForm
    template_name = 'partials/appointment/emergency_appointment.html'
    success_url = reverse_lazy('thanks-page')

    # success_message = _('Your request sent successfully.')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.status = 'APPROVED'
        form.instance.session_time = datetime.datetime.now().time()
        form.instance.doctor = Staff.objects.filter(city=self.request.POST['city']).order_by('?')[0]
        form.instance.type = 'EMERGENCY'
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(EmergencyAppointmentCreateView, self).get_form_kwargs()
        user = self.request.user

        if user:
            kwargs['user'] = user

        return kwargs

templates/partials/appointment/create_appointment.html
{% extends 'inner-page.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block breadcrumbs_title %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block breadcrumbs_text %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block inner_content %}

    <!-- ======= Appointment Section ======= -->

    <section id="appointment" class="appointment">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Make an Appointment</h2>
                <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem.
                    Sit sint
                    consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                    Quia
                    fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div>

            <form action="" method="post" role="form" data-aos="fade-up" data-aos-delay="100">
                <div class="row">
                    {% csrf_token %}
                    {% crispy form %}
                </div>
            </form>
        </div>
    </section><!-- End Appointment Section -->

{% endblock %}

templates/partials/appointment/emergency_appointment.html
{% extends 'inner-page.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block breadcrumbs_title %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block breadcrumbs_text %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block inner_content %}

    <!-- ======= Appointment Section ======= -->

    <section id="appointment" class="appointment">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <div class="alert alert-danger text-center mt-3" role="alert">
                    <h4 class="alert-heading">Emergency Appointment Case !!</h4>
                    <p>
                        Aww yeah, you successfully read this important alert message. This example text is going to run
                        a bit
                        longer
                        so that you can see how spacing within an alert works with this kind of content.
                    </p>
                    <hr>
                    <p class="mb-0">

                        Whenever you need to, be sure to use margin utilities to keep things nice and tidy.

                    </p>
                </div>


            </div>

            <form action="" method="post" role="form" data-aos="fade-up" data-aos-delay="100">
                <div class="row">

                    {% csrf_token %}
                    {% crispy form %}
                </div>
            </form>
        </div>
    </section><!-- End Appointment Section -->

{% endblock %}

templates/partials/appointment/list_user_appointment.html
{% extends "inner-page.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}


{% block title %}
    {% trans 'Appointemts List' %}
{% endblock %}

{% block breadcrumbs_title %}
    {% trans 'Appointemts List' %}
{% endblock %}

{% block breadcrumbs_text %}
    {% trans 'Appointemts List' %}
{% endblock %}



{% block inner_content %}

    <!-- ======= Appointment Section ======= -->

    <section id="appointment" class="appointment">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>{{ user.first_name }} {{ user.last_name }} {% trans 'Appointments' %}</h2>
            </div>

            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="pills-home-tab" data-toggle="pill" data-target="#pills-home"
                            type="button" role="tab" aria-controls="pills-home"
                            aria-selected="true">{% trans 'My Appointments' %}
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="pills-profile-tab" data-toggle="pill" data-target="#pills-profile"
                            type="button" role="tab" aria-controls="pills-profile"
                            aria-selected="false">{% trans 'My Equipement Reservations' %}
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="pills-contact-tab" data-toggle="pill" data-target="#pills-contact"
                            type="button" role="tab" aria-controls="pills-contact"
                            aria-selected="false">{% trans 'My Emargeny Appointments' %}
                    </button>
                </li>
            </ul>

            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                    <table class="table bg-white text-center">
                        <thead>
                        <tr class="bg-default tbl-header">
                            <th scope="col">{% trans 'Major' %}</th>
                            <th scope="col">{% trans 'Date' %}</th>
                            <th scope="col">{% trans 'Time' %}</th>
                            <th scope="col">{% trans 'Status' %}</th>
                            <th scope="col">{% trans 'Edit' %}</th>
                            <th scope="col">{% trans 'Cancel' %}</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for appointment in appointment %}
                            {% if appointment.type == 'NORMAL' %}
                            <tr class="bg-white">
                                <td>{{ appointment.major }}</td>
                                <td>{{ appointment.date }}</td>
                                <td>{{ appointment.get_session_time_display }}</td>
                                <td><span class="badge {% if appointment.status == 'BOOKED' %}alert-warning
                        {% elif appointment.status == 'DONE' %}alert-info{% endif %} rounded-pill"><i
                                        class="fa fa-circle mr-2"></i>{{ appointment.get_status_display }}</span></td>
                                <td><a href="{% url 'user-update-appointment' appointment.id %} "><i
                                        class="fa fa-edit "></i></a></td>
                                <td><a href="{% url 'delete-page' appointment.id %}"><i class="fa fa-trash text-danger"></i></a></td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                    <table class="table bg-white text-center">
                        <thead>
                        <tr class="bg-default tbl-header">
                            <th scope="col">{% trans 'Equipment' %}</th>
                            <th scope="col">{% trans 'Count' %}</th>
                            <th scope="col">{% trans 'city' %}</th>
                            <th scope="col">{% trans 'Address' %}</th>
                            <th scope="col">{% trans 'Duration From' %}</th>
                            <th scope="col">{% trans 'Duration To' %}</th>
                            <th scope="col">{% trans 'Delivery Way' %}</th>
                            <th scope="col">{% trans 'Total Price' %}</th>
                            <th scope="col">{% trans 'Edit' %}</th>
                            <th scope="col">{% trans 'Delete' %}</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for reservation in eq_reservation %}
                            <tr class="bg-white">
                                <td>{{ reservation.eq_name }}</td>
                                <td>{{ reservation.eq_count }}</td>
                                <td>{{ reservation.city }}</td>
                                <td>{{ reservation.address }}</td>
                                <td>{{ reservation.duration_from }}</td>
                                <td>{{ reservation.duration_to }}</td>
                                <td>{{ reservation.delivery_way }}</td>
                                <td>{{ reservation.price }}</td>

                                <td><a href="{% url 'edit-eq-reservation' reservation.id %} "><i class="fa fa-edit "></i></a></td>
                                <td><a href="{% url 'delete-eq-reservation' reservation.id %}"><i class="fa fa-trash text-danger"></i></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
                   <table class="table bg-white text-center">
                        <thead>
                        <tr class="bg-default tbl-header">
                            <th scope="col">{% trans 'Doctor' %}</th>
                            <th scope="col">{% trans 'Date' %}</th>
                            <th scope="col">{% trans 'Time' %}</th>
                            <th scope="col">{% trans 'Status' %}</th>
                            <th scope="col">{% trans 'Cancel' %}</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for appointment in appointment %}
                            {% if appointment.type == 'EMERGENCY' %}
                            <tr class="bg-white">
                                <td>{{ appointment.doctor }}</td>
                                <td>{{ appointment.date }}</td>
                                <td>{{ appointment.get_session_time_display }}</td>
                                <td><span class="badge {% if appointment.status == 'APPROVED' %}alert-success
                        {% elif appointment.status == 'DONE' %}alert-info{% endif %} rounded-pill"><i
                                        class="fa fa-circle mr-2"></i>{{ appointment.get_status_display }}</span></td>

                                <td><a href="{% url 'delete-page' appointment.id %}"><i class="fa fa-trash text-danger"></i></a></td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


        </div>
    </section><!-- End Appointment Section -->

{% endblock %}

templates/partials/appointment/thanks_page.html
{% extends 'inner-page.html' %}
{% load static %}
{% load i18n %}


{% block inner_content %}
    <div class="alert alert-success text-center mt-3" role="alert">
        <h4 class="alert-heading">{% trans 'Well done!' %}</h4>
        <p>
            {% blocktrans %}
                Aww yeah, you successfully read this important alert message. This example text is going to run a bit
                longer
                so that you can see how spacing within an alert works with this kind of content.
            {% endblocktrans %}
        </p>
        <hr>
        <p class="mb-0">
            {% blocktrans %}
                Whenever you need to, be sure to use margin utilities to keep things nice and tidy.
            {% endblocktrans %}
        </p>
    </div>

    <a href="{% url 'home' %}" class="btn btn-secondary">{% trans 'Back to home page' %}</a>
{% endblock %}

templates/partials/appointment/update_appointment.html
{% extends 'inner-page.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block breadcrumbs_title %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block breadcrumbs_text %}
    {% trans 'Appointemt' %}
{% endblock %}

{% block inner_content %}

    <!-- ======= Appointment Section ======= -->

    <section id="appointment" class="appointment">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Make an Appointment</h2>
                <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem.
                    Sit sint
                    consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                    Quia
                    fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div>

            <form action="" method="post" role="form" data-aos="fade-up" data-aos-delay="100">
                <div class="row">
                    {% csrf_token %}
                    {% crispy form %}
                </div>
            </form>
        </div>
    </section><!-- End Appointment Section -->

{% endblock %}